#!/bin/bash
# Calculate sunrise and sunset times for San Diego, CA on 2026-01-31

# San Diego, CA coordinates
LATITUDE=32.7157
LONGITUDE=-117.1611

# Date: January 31, 2026
YEAR=2026
MONTH=1
DAY=31

./sunrise $LATITUDE $LONGITUDE $YEAR $MONTH $DAY

# Date: January 31, 2026
YEAR=2026
MONTH=2
DAY=1

./sunrise $LATITUDE $LONGITUDE $YEAR $MONTH $DAY
DAY=2


./sunrise $LATITUDE $LONGITUDE $YEAR $MONTH $DAY
DAY=3


./sunrise $LATITUDE $LONGITUDE $YEAR $MONTH $DAY
DAY=4

./sunrise $LATITUDE $LONGITUDE $YEAR $MONTH $DAY
DAY=5

./sunrise $LATITUDE $LONGITUDE $YEAR $MONTH $DAY
DAY=6

./sunrise $LATITUDE $LONGITUDE $YEAR $MONTH $DAY

